version: '2'
services:
    xnat-web:
       build: ./tomcat
       ports:
        - "8081:8080"
       volumes:
         - ./webapps:/opt/tomcat/webapps
         - /var/run/docker.sock:/var/run/docker.sock
       expose:
        - "8080"
       links:
        - xnat-db
    xnat-db:
       build: ./postgres
       expose:
         - "5432"
       volumes:
         - ./postgres-data:/var/lib/postgresql/data
    xnat-nginx:
       build: ./nginx
       ports:
        - "80:80"
       expose:
        - "80"
       links:
         - xnat-web

    prometheus:
       image: prom/prometheus
       volumes:
            - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
       command:
            - '--config.file=/etc/prometheus/prometheus.yaml'
       ports:
            - '9090:9090'
       links:
            - cadvisor
    cadvisor:
        image: google/cadvisor
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        ports:
        - "8082:8080"
        expose:
          - 8082
